-- MySQL Script generated by MySQL Workbench
-- Sat Jun 19 21:55:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vemdaterra
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vemdaterra
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vemdaterra` DEFAULT CHARACTER SET utf8 ;
USE `vemdaterra` ;

-- -----------------------------------------------------
-- Table `vemdaterra`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vemdaterra`.`Vendedor` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj/cpf` VARCHAR(45) NOT NULL,
  `lozalização` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idVendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vemdaterra`.`Cupom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vemdaterra`.`Cupom` (
  `idCupom` INT NOT NULL AUTO_INCREMENT,
  `valordesconto` DOUBLE NOT NULL,
  `localdetroca` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idCupom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vemdaterra`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vemdaterra`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `telefone` INT NOT NULL,
  `` VARCHAR(260) NOT NULL,
  `cartao` INT NOT NULL,
  `cupom` TINYINT NOT NULL,
  `Cupom_idCupom` INT NOT NULL,
  `Cupom_idCupom1` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Cupom_idCupom`),
  INDEX `fk_Cliente_Cupom1_idx` (`Cupom_idCupom1` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Cupom1`
    FOREIGN KEY (`Cupom_idCupom1`)
    REFERENCES `vemdaterra`.`Cupom` (`idCupom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vemdaterra`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vemdaterra`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `descricao` VARCHAR(260) NOT NULL,
  `valor` DECIMAL(5,2) NOT NULL,
  `codigo` VARCHAR(10) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `Vendedor_idVendedor` INT NOT NULL,
  `Cupom_idCupom` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Cliente_Cupom_idCupom` INT NOT NULL,
  PRIMARY KEY (`idProduto`, `Vendedor_idVendedor`, `Cliente_idCliente`, `Cliente_Cupom_idCupom`),
  INDEX `fk_Produto_Vendedor_idx` (`Vendedor_idVendedor` ASC) VISIBLE,
  INDEX `fk_Produto_Cupom1_idx` (`Cupom_idCupom` ASC) VISIBLE,
  INDEX `fk_Produto_Cliente1_idx` (`Cliente_idCliente` ASC, `Cliente_Cupom_idCupom` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Vendedor`
    FOREIGN KEY (`Vendedor_idVendedor`)
    REFERENCES `vemdaterra`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Cupom1`
    FOREIGN KEY (`Cupom_idCupom`)
    REFERENCES `vemdaterra`.`Cupom` (`idCupom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Cliente1`
    FOREIGN KEY (`Cliente_idCliente` , `Cliente_Cupom_idCupom`)
    REFERENCES `vemdaterra`.`Cliente` (`idCliente` , `Cupom_idCupom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vemdaterra`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vemdaterra`.`endereco` (
  `idendeereco` VARCHAR(10) NOT NULL,
  `logradouro` VARCHAR(80) NOT NULL,
  `cep` INT NOT NULL,
  `bairro` VARCHAR(60) NOT NULL,
  `numero` INT NOT NULL,
  `cidade` VARCHAR(60) NOT NULL,
  `estado` VARCHAR(80) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Vendedor_idVendedor` INT NOT NULL,
  PRIMARY KEY (`idendeereco`, `Cliente_idCliente`, `Vendedor_idVendedor`),
  INDEX `fk_endereco_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_endereco_Vendedor1_idx` (`Vendedor_idVendedor` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `vemdaterra`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_Vendedor1`
    FOREIGN KEY (`Vendedor_idVendedor`)
    REFERENCES `vemdaterra`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
